name: Build and Publish Docker Images
on: [workflow_dispatch, push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build ./api/ -t mmazaboys/devops-qr-code-backend:latest
          docker push mmazaboys/devops-qr-code-backend:latest

      - name: Build and push frontend image
        run: |
          docker build ./front-end-nextjs/ -t mmazaboys/devops-qr-code-frontend:latest
          docker push mmazaboys/devops-qr-code-frontend:latest