name: Build and Publish Docker Images
on: 
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mahmoud00thedev
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build ./front-end-nextjs/ -t mahmoud00thedev/devops-qr-code-frontend:latest
          docker push mahmoud00thedev/devops-qr-code-frontend:latest

      - name: Build and push backend image
        run: |
          docker build ./api/ -t mahmoud00thedev/devops-qr-code-backend:latest
          docker push mahmoud00thedev/devops-qr-code-backend:latest